name: E2E

on:
  check_run:
    types:
    - rerequested
    - requested_action
  pull_request:
    branches:
    - $default-branch
  push:
    branches:
    - $default-branch
    tags:
    - v*

jobs:
  test:
    needs:
    - build-images
    strategy:
      matrix:
        kubernetes-version: [v1-16, v1-17, v1-18]
    runs-on: ubuntu-latest
    steps:
    - name: Install KinD
      run: |
        curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64
        chmod +x /usr/local/bin/kind

    - name: Test on Kubernetes ${{ matrix.kubernetes-version }}
      run: |
        make e2e.${{ matrix.kubernetes-version }}
