name: Test

on:
  check_run:
    types:
    - rerequested
    - requested_action
  pull_request:
    branches:
    - $default-branch
  push:
    branches:
    - $default-branch
    tags:
    - v*

jobs:
  test:
    needs:
    - check
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
